# Generated by Django 4.1.4 on 2023-03-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_page_block'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='second_name',
        ),
        migrations.AlterField(
            model_name='block',
            name='type',
            field=models.CharField(choices=[('Текст', 'Text'), ('Изображение', 'Image')], default='Текст', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(default='status', max_length=255),
        ),
    ]
