# Generated by Django 4.1.4 on 2023-04-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_user_avatar_remove_user_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='prev_block_id',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='block',
            name='type',
            field=models.CharField(choices=[('Текст', 'Text'), ('Изображение', 'Image')], default='Текст', max_length=255),
        ),
    ]
